ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', include("store.urls")),
    path('home', include("store.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home.as_view(), name="home" ),
    path('store/', home.as_view(), name="home" ),
    path('home/', home.as_view(), name="home" ),
    path('about/', about.as_view(), name="about"),
    path('login/', login.as_view(), name="login"),
    path('product/<int:pk>/', product.as_view(), name="product"),
    path('search/', search.as_view(), name="search"),
    path('search/<int:id_cate>', search.as_view(), name="search"),
    path('categories/', categories.as_view(), name="categories"),
    path('product_new/', product_new.as_view(), name="product_new"),
    path('product_upd/<int:id>', product_upd.as_view(), name="product_upd"),
    path('product_del/<int:id>', product_del.as_view(), name="product_del"),
    path('cart_add/<int:pid>', cart_add.as_view(), name="cart_add"),
    path('cart', cart.as_view(), name="cart"),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls.base import reverse

# Create your models here.
class Category(models.Model):
    description = models.CharField(max_length=255, null=False, verbose_name="Descripción")

    def __str__(self):
        return f"{self.description}"

class Product(models.Model):
    name = models.CharField(max_length=255, null=False, verbose_name="Nombre")
    image = models.FileField(upload_to='img/', verbose_name="Imagen", null=True)
    description = models.TextField(verbose_name="Descripción")
    price= models.FloatField(verbose_name="Precio")
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="product_category", verbose_name="Categoria")

    def __str__(self):
        return f"{self.name} precio: {self.price}"

    def get_absolute_url(self):
        return reverse("product", kwargs={"pk":self.id})

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True, related_name="products", verbose_name="Productos")

    def __str__(self):
        return f"{self.user.username}"

store/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):

    price = forms.DecimalField(initial=0.00)
    description = forms.CharField(label="Descripción",widget=forms.Textarea(attrs={"title":"Descripción detalla del producto", "rows":10, "cols":90}))

    class Meta:
        model = Product
        fields = ('name', 'image', 'description', 'category_id', 'price')

store/views.py
from django.shortcuts import get_object_or_404, render
from django.http.response import HttpResponseRedirect
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse
from .models import Category, Product
from .forms import ProductForm
from django.db.models.query_utils import Q
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

#from django.contrib.auth.mixins import LoginRequiredMixin
#from django.contrib.auth.mixins import PermissionRequiredMixin


# Create your views here.
#LoginRequiredMixin, 

#class MyView(LoginRequiredMixin, View):
#    login_url = '/login/'
#    redirect_field_name = 'redirect_to'

#PermissionRequiredMixin
#class MyView(PermissionRequiredMixin, View):
    #permission_required = 'polls.add_choice'
    # Or multiple of permissions:
    #permission_required = ('polls.view_choice', 'polls.change_choice')

class base(View):
    template_name = ""
    companyname = "JAGUARETE KAA S.A."
    bcontent = {"company_name": companyname,
                "copyright": "Copyright 2021",
                "ndeveloper": "por David Luna"
               }

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, self.bcontent)

class home(base):
    template_name = "store/home.html"
    base.bcontent.update({"products_top3": Product.objects.all()[:3],
                          "products_next": Product.objects.all()[3:10]})

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.bcontent)

class about(base):
    template_name = "store/about.html"
    bcontent = {"app_name": "OLEC - e-commerce",
                "app_ver": "v1.0",
                "app_desc": "Trabajo final - Portal e-commerce"
               }
    def get(self, request):
        return render(request, self.template_name, self.bcontent)

class product(base, DetailView):
    model = Product
    template_name = "store/product.html"
    context_object_name="product"
    
    bcontent = {"app_name": "OLEC - e-commerce",
                "app_ver": "v1.0",
                "app_desc": "Trabajo final - Portal e-commerce"
               }

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    

class categories(base, ListView):
    model = Category
    template_name = "store/categories.html"
    context_object_name="categories"

    def get_context_data(self, **kwargs):
        context = super(categories, self).get_context_data(**kwargs)
        context.update(self.bcontent)
        return context

class login(base):
    template_name = "store/login.html"

class search(base):
    template_name = "store/search.html"

    def get(self, request, *args, **kwargs):
        print("metodo get de search")
        s_category = self.kwargs['id_cate']
        if s_category:
            search_resu = Product.objects.filter(category_id=s_category)
        base.bcontent.update({"search_resu":search_resu})
        return render(request, self.template_name, self.bcontent)

    def post(self, request, *args, **kwargs):
        print("metodo post de search")
        s_name_desc = request.POST.get('s_name_desc')
        s_category =  request.POST.get('s_category')
        if s_name_desc:
            search_resu = Product.objects.filter(Q(name__contains=s_name_desc)|Q(description__contains=s_name_desc))
        elif s_category:
            search_resu = Product.objects.filter(category_id=s_category)
        print(search_resu)
        base.bcontent.update({"search_resu":search_resu})
        return render(request, self.template_name, self.bcontent)

class user_register(base):
    template_name = "store/user_register.html"

class product_new(CreateView):
    template_name = "store/product_new.html"
    form_class = ProductForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        return super().form_valid(form)

class product_upd(UpdateView):
    template_name = "store/product_upd.html"
    form_class = ProductForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        return super().form_valid(form)

    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Product, id=id)

    def get_success_url(self):
        id = self.kwargs.get("id")
        return reverse("product", kwargs={"pk":id})


class product_del(DeleteView):
    template_name = "store/product_del.html"
    form_class = ProductForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Product, id=id_)

    def get_success_url(self):
        return reverse("home")

class cart_add(base):
    template_name = "store/cart.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

class cart(base):
    template_name = "store/cart.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

store/templates/store/about.html
{% extends "store/base.html" %}
{% block body %}
    <h1>About</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pharetra eget quam ut finibus. Vestibulum vel ex vitae nisi vulputate pretium. Suspendisse ullamcorper molestie est, sed sollicitudin mi tristique a. Nunc at tristique eros. Morbi a diam purus. In tempor, orci sed pellentesque ornare, libero est pretium velit, vestibulum commodo ligula diam id lacus. Quisque lobortis felis nisi, ac aliquet leo rhoncus sed. In varius enim id odio scelerisque faucibus. Pellentesque odio est, venenatis quis arcu a, posuere porta sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nullam faucibus lorem eget ligula vulputate condimentum.

        Sed bibendum felis non mi dapibus, non imperdiet eros hendrerit. Maecenas consequat, odio vitae faucibus tempus, metus dui dignissim turpis, id interdum urna neque eget lacus. Nulla ultricies, massa eget aliquam aliquam, sem ante sodales magna, vel ultrices neque nulla nec orci. Mauris sodales risus sed fermentum tincidunt. Nulla nec mauris vitae dui rutrum lobortis. Nam vel arcu eu lacus cursus convallis. Quisque quis nibh et nulla euismod rutrum et et tortor. Phasellus quis lectus accumsan, pharetra elit in, aliquam tortor. Fusce ac ex consequat, molestie tellus non, blandit enim. In tincidunt eget purus quis pellentesque. Sed consectetur sem ut suscipit commodo. In hac habitasse platea dictumst. Mauris in erat quis mi semper tincidunt molestie vel massa.
        
        Phasellus vitae lectus ut odio imperdiet molestie. Morbi id risus a tortor ullamcorper ullamcorper. Donec ipsum arcu, posuere efficitur nulla ut, semper efficitur erat. Nam eu posuere nisl, vel cursus velit. Nulla non eros turpis. Integer lacinia elementum elit. Nulla ut malesuada nulla. Phasellus accumsan quis orci tristique gravida. Morbi id leo odio. Pellentesque sollicitudin mattis arcu in bibendum.
        
        Quisque ut nisi sed ipsum porttitor rutrum eget viverra dolor. Phasellus consectetur mollis purus sed elementum. Aliquam dapibus velit fringilla, posuere ex a, iaculis quam. Maecenas egestas nisl nec est semper facilisis a non neque. Ut vestibulum dui a tempor convallis. Quisque et semper turpis. Vestibulum sit amet velit vitae lorem consectetur lobortis quis ac odio. Suspendisse accumsan, velit nec pharetra aliquam, lectus ex gravida elit, at imperdiet nibh lorem id sapien. Suspendisse scelerisque nunc quis diam volutpat, accumsan finibus velit pellentesque. Vivamus venenatis erat massa, vitae pretium quam vulputate vitae. Ut purus leo, tincidunt eget felis sit amet, eleifend euismod nisi. In hac habitasse platea dictumst. Mauris eget lacus sed augue dictum lobortis. Curabitur vitae tempor nulla, congue ultricies mi.
        
        Nulla facilisi. Pellentesque interdum odio in mauris laoreet dictum. Phasellus in velit faucibus, malesuada ipsum ac, cursus nunc. Nulla non quam eu turpis efficitur placerat id non nibh. Cras volutpat felis quis magna mollis congue. Praesent ut elit suscipit, convallis nibh porttitor, euismod risus. Nunc lacinia vitae metus in gravida.</p>
    <p>{{app_name}}</p>
    <p>{{app_ver}}</p>
    <p>{{app_desc}}</p>
{% endblock %}

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'store/css/styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

        <title>Store</title>
    </head>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark">
            <p><img width="150" id="base-header-img" src="{{ MEDIA_URL }}img/jk.png" alt="Imagen Compañia"></p>
            <ul class="navbar-nav ml-auto" >
                {% if user.is_authenticated %}
                    <li class="nav-link">Usuario: {{ user.get_full_name }}</li> <a role="button" class="btn btn-outline-primary" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
                {% else %}                  
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                {% endif %}
                
                <li class="nav-item"><a class="nav-link" href="#">Registro</a></li>
                {% if perms.store.view_shop_cart or not user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'cart' %}">Carrito</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock %}

    {% block base %}
    <body>
        <div id="base-menu" class="navbar navbar-expand-sm navbar-dark" style="background-color: #e3f0fd;">
            
            <div id="menu-buttons" class="navbar-collapse">
                <a class="nav-link active" href="{% url 'home' %}">Home</a>
                <a class="nav-link active" href="{% url 'categories' %}">Categorias</a>
                <a class="nav-link active" href="{% url 'about' %}">Acerca de...</a>
                <a class="nav-link active" href="mailto:dhluna@gmail.com">Contacto</a>
                {% if perms.store.add_product %}
                <a class="nav-link active" href="{% url 'product_new' %}">Nuevo producto</a>
                {% endif %}
            </div>
            <div id="menu-search">
                <form action="{% url 'search' %}" method="POST">                
                <div class="input-group mb-2">
                    {% csrf_token %}
                    <input type="text" class="form-control" name="s_name_desc" placeholder="producto/descripción" aria-label="Example text with button addon" aria-describedby="button-addon1">
                    <button type="submit" class="btn btn-outline-secondary" type="button" id="button-addon2">Buscar</button>
                </div>
                </form>
            </div>
        </div>
        {% block body %}
        {% endblock %}
    </body>
    {% endblock %}

    <footer>
        <div id="footer" class="shadow p-3 mb-5 bg-body rounded">
            <div>{{company_name}}</div>
            <div>{{copyright}}</div>
            <div>{{ndeveloper}}</div>
        </div>
    </footer>
</html>

store/templates/store/cart.html
{% extends "store/base.html" %}
{% block body %}

<ul>
    <li>Carrito en construcción....</li>
</ul>

<div>
    <a href="../../" class="btn btn-primary me-md-2">Atras</a>
</div>

{% endblock %}

store/templates/store/categories.html
{% extends "store/base.html" %}
{% block body %}
<div class="shadow-sm p-3 mb-5 bg-body rounded"><p class="fs-1">Categorias</p></div>

<ul class="list-group">
{% for cate in categories%}

<a href="{% url 'search' cate.id %}" class="list-group-item list-group-item-action list-group-item-light">{{cate.description}}</a>
{% endfor %}
</ul>

{% endblock %}

store/templates/store/home.html
{% extends "store/base.html" %}
{% block body %}
<div id="prod-list" class="row">
        {% for prod in products_top3 %}
          <div class="col-sm-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{prod.name}}</h5>
              </div>
              <img id="prod_image" src="{{ media_url  }}{{ prod.image.url }}" class="card-img-top" alt="{{ prod.image.name }}">
              <a href="{% url 'product' prod.id %}" class="btn btn-primary">Ver</a>
            </div>
          </div>  
        {% empty %}
          <div class="card-body">No hay productos.</div>
        {% endfor %}
      </div>
<br>
        <div class="list-group">
          {% for prod in products_next %}
          <a href="{% url 'product' prod.id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">{{prod.name}}</h5>
            </div>
            <p class="text-muted">{{prod.description}}</p>
          </a>
          {% endfor %}
        </div>

{% endblock %}

store/templates/store/product.html
{% extends "store/base.html" %}
{% block body %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ media_url  }}{{ product.image.url }}" width="200" class="img-fluid rounded-start" alt="{{ product.image.name }}">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{product.name}}</h5>
        <a href="{% url 'search' product.category_id.id %}" class="list-group-item list-group-item-action list-group-item-light">Categoria: {{product.category_id}}</a>
        <p class="card-text">{{ product.description }}</p>
        <p class="card-text"><small class="text-muted">Precio: $ {{ product.price }}</small></p>
        {% if perms.store.view_shop_cart or not user.is_authenticated %}
        <a href="{% url 'cart_add' product.id %}" class="btn btn-outline-success">Agregar al carrito</a>
        {% endif %}
      </div>
    </div>
    
    <div class="col-md-8">
      <div class="card-body">
        {% if perms.store.change_product %}
        <a href="{% url 'product_upd' product.id %}" class="btn btn-outline-success">Editar</a>
        {% endif %}

        {% if perms.store.delete_product %}
        <a href="{% url 'product_del' product.id %}" class="btn btn-outline-success">Borrar</a>
        {% endif %}
      </div>
    </div>
    
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <a href="../../" class="btn btn-primary me-md-2">Atras</a>
    </div>

    <p></p>
  </div>
</div>

{% endblock %}

store/templates/store/product_del.html
{% extends "store/base.html" %}

{% block body %}

<form enctype="multipart/form-data" action="" method="POST">{% csrf_token %}
    <h1>Seguro que desea borrar el producto "{{product.name}}"?</h1>
    <input type="submit" value="Si">
    <a id="links" class="cancel" href="../">Cancelar</a>
</form>

{% endblock %}

store/templates/store/product_new.html
{% extends "store/base.html" %}

{% block body %}

<form enctype="multipart/form-data" action="." method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
    <a id="links" class="cancel" href="../">Cancelar</a>
</form>

{% endblock %}

store/templates/store/product_upd.html
{% extends "store/base.html" %}

{% block body %}

<form enctype="multipart/form-data" action="" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
    <a id="links" class="cancel" href="../">Cancelar</a>
</form>

{% endblock %}

store/templates/store/search.html
{% extends "store/base.html" %}
{% block body %}

<div class="shadow-sm p-3 mb-5 bg-body rounded"><p class="fs-1">Productos</p></div>
{% if search_resu %}
<div class="list-group"></div>
{% for prod in search_resu%}
    <a href="{% url 'product' prod.id %}" class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">{{prod.name}}</h5>
      </div>
      <p class="text-muted">{{prod.description}}</p>
    </a>
    {% endfor %}
  </div>
{% else %}
<div class="alert alert-warning" role="alert">
  No se encontraron coincidencias con tu búsqueda
</div>  
{% endif %}

{% endblock %}

store/templates/store/user_register.html
{% extends "store/base.html" %}
{% block body %}


{% endblock %}